[tox]
skipsdist = True

[testenv:ui]
description = Run Playwright E2E UI tests (requires Caldera installed with magma as plugin)
deps =
    -r{toxinidir}/requirements-ui-tests.txt
    pytest
    pytest-asyncio==0.26.0
    pyyaml
allowlist_externals =
    bash
    nodeenv
    npm
    playwright
skip_install = true
commands =
    nodeenv --node=20.11.0 --python-virtualenv --prebuilt --quiet
    bash -c "npm ci --prefer-offline && npm run build"
    playwright install chromium
    pytest tests/e2e --tb=short -v {posargs}
